export const TX_SUMMARY_COLUMNS = [
  'tx_id',
  'sender_address',
  'sponsor_address',
  'sponsor_nonce',
  'nonce',
  'fee_rate',
  'block_height',
  'block_hash',
  'index_block_hash',
  'block_time',
  'tx_index',
  'microblock_sequence',
  'burn_block_height',
  'burn_block_time',
  'status',
  'type_id',
  'token_transfer_recipient_address',
  'token_transfer_amount',
  'token_transfer_memo',
  'smart_contract_clarity_version',
  'smart_contract_contract_id',
  'contract_call_contract_id',
  'contract_call_function_name',
  'coinbase_alt_recipient',
  'tenure_change_cause',
];

// Heavy columns (post_conditions, raw_result, smart_contract_source_code,
// contract_call_function_args) live in TX_HEAVY_COLUMNS in `pg-store-v3.ts` and are
// opted in per-query via `include`, so they're omitted from the base list.
export const TX_COLUMNS = [
  ...TX_SUMMARY_COLUMNS,
  'parent_block_hash',
  'parent_index_block_hash',
  'event_count',
  'execution_cost_read_count',
  'execution_cost_read_length',
  'execution_cost_runtime',
  'execution_cost_write_count',
  'execution_cost_write_length',
  'vm_error',
  'coinbase_payload',
  'coinbase_vrf_proof',
  'tenure_change_tenure_consensus_hash',
  'tenure_change_prev_tenure_consensus_hash',
  'tenure_change_burn_view_consensus_hash',
  'tenure_change_previous_tenure_end',
  'tenure_change_previous_tenure_blocks',
  'tenure_change_pubkey_hash',
];

export const MEMPOOL_TX_SUMMARY_COLUMNS = [
  'tx_id',
  'type_id',
  'status',
  'sender_address',
  'nonce',
  'sponsor_address',
  'sponsor_nonce',
  'fee_rate',
  'receipt_time',
  'receipt_block_height',
  'token_transfer_recipient_address',
  'token_transfer_amount',
  'token_transfer_memo',
  'smart_contract_clarity_version',
  'smart_contract_contract_id',
  'contract_call_contract_id',
  'contract_call_function_name',
  'coinbase_alt_recipient',
  'tenure_change_cause',
];

// Heavy columns (post_conditions, smart_contract_source_code,
// contract_call_function_args) live in MEMPOOL_TX_HEAVY_COLUMNS in `pg-store-v3.ts` and
// are opted in per-query via `include`, so they're omitted from the base list.
export const MEMPOOL_TX_COLUMNS = [
  ...MEMPOOL_TX_SUMMARY_COLUMNS,
  'replaced_by_tx_id',
  'coinbase_payload',
  'coinbase_vrf_proof',
  'tenure_change_tenure_consensus_hash',
  'tenure_change_prev_tenure_consensus_hash',
  'tenure_change_burn_view_consensus_hash',
  'tenure_change_previous_tenure_end',
  'tenure_change_previous_tenure_blocks',
  'tenure_change_pubkey_hash',
];
