import { FastifyPluginAsync } from 'fastify';
import { Server } from 'node:http';
import { TypeBoxTypeProvider } from '@fastify/type-provider-typebox';
import { STACKS_MAINNET } from '@stacks/network';
import { handleBurnchainChainTipCache } from '../../controllers/cache-controller.js';
import { StakingRewardsSchema } from '../../schemas/v3/entities/staking-rewards.js';

/**
 * BTC burned on mainnet by the 2.0-era PoX sunset-ramp surcharge (bitcoin blocks ~766050-781551),
 * in satoshis. The node never reported these burns in its burn block events, so they are added as a
 * fixed historical total.
 */
const MAINNET_SUNSET_BURN_AMOUNT = 489352064n;

export const StakingRewardsRoutes: FastifyPluginAsync<
  Record<never, never>,
  Server,
  TypeBoxTypeProvider
> = async fastify => {
  fastify.get(
    '/staking/rewards',
    {
      preHandler: handleBurnchainChainTipCache,
      schema: {
        operationId: 'get_staking_rewards',
        summary: 'Get network staking reward totals',
        description:
          'Get the total Bitcoin generated by staking on the Stacks network across all history, ' +
          'along with the total BTC burned by block commits. Values are in satoshis and always ' +
          'reflect the latest ingested chain state.',
        tags: ['Staking'],
        response: {
          200: StakingRewardsSchema,
        },
      },
    },
    async (_req, reply) => {
      const totals = await fastify.db.v3.getStakingRewards();
      const sunsetBurnAmount =
        fastify.chainId === STACKS_MAINNET.chainId ? MAINNET_SUNSET_BURN_AMOUNT : 0n;
      const rewardAmount = BigInt(totals.reward_amount);
      const burnAmount = BigInt(totals.burn_amount) + sunsetBurnAmount;
      await reply.send({
        btc: {
          reward_amount: rewardAmount.toString(),
          burn_amount: burnAmount.toString(),
          total_amount: (rewardAmount + burnAmount).toString(),
        },
      });
    }
  );
};
