import { FastifyPluginAsync } from 'fastify';
import { Server } from 'node:http';
import { TypeBoxTypeProvider } from '@fastify/type-provider-typebox';
import { handleChainTipCache } from '../../controllers/cache-controller.js';
import { StakingRewardsSchema } from '../../schemas/v3/entities/staking-rewards.js';

export const StakingRewardsRoutes: FastifyPluginAsync<
  Record<never, never>,
  Server,
  TypeBoxTypeProvider
> = async fastify => {
  fastify.get(
    '/staking/rewards',
    {
      preHandler: handleChainTipCache,
      schema: {
        operationId: 'get_staking_rewards',
        summary: 'Get network staking reward totals',
        description:
          'Get the total Bitcoin generated by staking on the Stacks network across all history, ' +
          'along with the total BTC burned by block commits. Values are in satoshis and always ' +
          'reflect the latest ingested chain state.',
        tags: ['Staking'],
        response: {
          200: StakingRewardsSchema,
        },
      },
    },
    async (_req, reply) => {
      const totals = await fastify.db.v3.getStakingRewards();
      await reply.send({
        btc: {
          reward_amount: totals.reward_amount,
          burn_amount: totals.burn_amount,
          total_amount: (BigInt(totals.reward_amount) + BigInt(totals.burn_amount)).toString(),
        },
      });
    }
  );
};
