version: "3.9"
services:
  bitcoind:
    image: "ruimarinho/bitcoin-core:0.20"
    ports:
      - "18443:18443"
      - "18444:18444"
    command: 
      -printtoconsole
      -regtest=1
      -disablewallet=0
      -txindex=1
      -server=1
      -discover=0
      -dns=0
      -dnsseed=0
      -listenonion=0
      -rpcserialversion=0
      -rest
      -bind=0.0.0.0:18444
      -rpcbind=0.0.0.0:18443
      -rpcallowip=0.0.0.0/0
      -rpcallowip=::/0
      -rpcuser=krypton
      -rpcpassword=krypton
  bitcoind-mine-initial:
    image: "curlimages/curl:latest"
    depends_on:
      - bitcoind
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 1000
        window: 360s
    environment:
      - BTC_ADDR=miEJtNKa3ASpA19v5ZhvbKTEieYjLpzCYT
      - INIT_BLOCKS=101
      - MINE_INTERVAL=2.5s
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        rpc(){
          params=$$(local IFS=","; shift; echo "$$*";)
          body='{"jsonrpc":"1.0","id":"c","method":"'$$1'","params":['$$params']}'
          echo "Sending RPC payload: $$body" >&2
          curl -sS --fail-with-body -u krypton:krypton -H 'content-type: text/plain;' --data-binary "$$body" http://bitcoind:18443
        }
        rpc importaddress \"$$BTC_ADDR\" '""' false
        echo "Mining initial $$INIT_BLOCKS blocks to $$BTC_ADDR"
        rpc generatetoaddress $$INIT_BLOCKS \"$$BTC_ADDR\"
        while true; do
          echo "checking txs"
          tx=$$(rpc listtransactions \"*\" 1 0 true)
          case "$$tx" in
          *send*)
            echo "Detected Stacks mining tx, starting btc auto-mining..."
            break
            ;;
          esac
          sleep 1s
        done
        while true; do
          rpc generatetoaddress 1 \"$$BTC_ADDR\"
          sleep $$MINE_INTERVAL
        done
