
version: '3.7'
services:
  stacks-blockchain:
    image: "hirosystems/stacks-api-e2e:stacks2.1-a50d830"
    command: |
      bash -c "rm /event-log.ndjson && /root/run.sh"
    ports:
      - "18443:18443" # bitcoin regtest JSON-RPC interface
      - "18444:18444" # bitcoin regtest p2p
      - "20443:20443" # stacks-node RPC interface
      - "20444:20444" # stacks-node p2p
    environment:
      MINE_INTERVAL: 1s
      STACKS_EVENT_OBSERVER: host.docker.internal:30445
      # STACKS_LOG_TRACE: 1
      # STACKS_LOG_DEBUG: 1
    extra_hosts:
      - "host.docker.internal:host-gateway" # fixes `host.docker.internal` on linux hosts
  stacks-subnet:
    # restart: on-failure
    image: "hirosystems/stacks-subnets:7012d22"
    # build:
    #   dockerfile: ./subnet-node.Dockerfile
    command: subnet-node start --config /app/config/Stacks-subnet.toml
    ports:
      - "30443:30443" # subnet-node RPC interface
      - "30444:30444" # subnet-node p2p
      - "30445:30445" # subnet-node event-observer
    environment:
      STACKS_EVENT_OBSERVER: host.docker.internal:3700
      # STACKS_LOG_TRACE: 1
      # STACKS_LOG_DEBUG: 1
    volumes:
      - ../stacks-blockchain/:/app/config
    extra_hosts:
      - "host.docker.internal:host-gateway" # fixes `host.docker.internal` on linux hosts
