version: "3"
services:
  rosetta-cli:
    build:
      context: ../rosetta-cli-config
      dockerfile: docker/Dockerfile
    command: /bin/rosetta-cli --configuration-file /app/rosetta-config-docker.json check:construction
