services:
  # clarinet-builder:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.clarinet-builder
  #   networks:
  #     - backend

  clarinet-devnet:
    # depends_on:
    #   - clarinet-builder
    # network_mode: "host"  # equivalent to --network host
    networks:
      - backend
    restart: on-failure
    build:
      context: .
      # platform: ${BUILDPLATFORM:-linux/amd64}
    ports:
      - "20443:20443"
      - '20444:20444'
      - "18443:18443"
      - "5490:5490"
    volumes:
      - chainstate:/chainstate
      - ../stacks-blockchain/:/app/config
      - ../stacks-blockchain/.chaindata:/tmp/stacks-blockchain-data
    environment:
      - PG_DATABASE=stacks_blockchain_api
      - POSTGRES_DB=stacks_blockchain_api
      - STACKS_CHAIN_ID=0x80000000
    extra_hosts:
      - 'host.docker.internal:host-gateway' # fixes `host.docker.internal` on linux hosts
    privileged: true

networks:
  backend:
volumes:
  chainstate:
