# Dockerfile.clarinet-builder

FROM --platform=$BUILDPLATFORM rust:alpine as builder

WORKDIR /usr/src/

RUN apk add --no-cache \
    git \
    build-base \
    curl \
    pkgconfig

# Build Clarinet from source
RUN git clone https://github.com/hirosystems/clarinet.git && \
    cd clarinet && \
    git checkout main && \
    cargo build --release

# This image produces the built Clarinet binary
