import { Static, Type } from '@sinclair/typebox';
import { AmountSchema } from './common.js';

/** Network-wide staking reward totals, always as of the latest ingested chain state. */
export const StakingRewardsSchema = Type.Object(
  {
    btc: Type.Object({
      reward_amount: Type.String({
        ...AmountSchema,
        description:
          'Total Bitcoin generated by staking on the Stacks network, in satoshis, counted as the ' +
          'BTC paid by block commits to reward recipients: stacker reward addresses directly ' +
          'through pox-4, and the sBTC peg custody address from pox-5 on (whose inflows fund the ' +
          'sBTC staking rewards distributed through the pox-5 contract).',
        examples: ['9232234450122'],
      }),
      burn_amount: Type.String({
        ...AmountSchema,
        description:
          'Total BTC burned by block commits, in satoshis, including pox-1 through pox-4 ' +
          'prepare-phase burns. Excludes the 2.0-era PoX sunset-ramp surcharge (bitcoin blocks ' +
          '~766050-781551), which the node never reported. pox-5 commits do not burn.',
        examples: ['184023450122'],
      }),
      total_amount: Type.String({
        ...AmountSchema,
        description:
          'Sum of `reward_amount` and `burn_amount`, in satoshis: the total BTC block commits ' +
          'have spent toward staking across all history, whether paid to recipients or burned.',
        examples: ['9416257900244'],
      }),
    }),
  },
  { title: 'StakingRewards' }
);
export type StakingRewards = Static<typeof StakingRewardsSchema>;
